"use client";

import Link from "next/link";
import { useState } from "react";
import type { Snapshot } from "./types";
import { shortId, reportCount, stageFor, STAGES } from "./mend";

export function MetricsView({snapshot}:{snapshot:Snapshot}) {
  const [anchor] = useState(()=>Date.now());
  const days = Array.from({length:7},(_,index)=>{const date=new Date(anchor-(6-index)*86400000);return {key:date.toISOString().slice(0,10),label:date.toLocaleDateString("en-GB",{weekday:"short"}),date};});
  const windowStart = new Date(days[0].key).getTime();
  const cases = snapshot.cases.filter(item=>new Date(item.createdAt).getTime()>=windowStart);
  const daily = days.map(day=>({ ...day,x:cases.filter(item=>item.sourcePlatform==="x" && item.createdAt.startsWith(day.key)).reduce((sum,item)=>sum+reportCount(item),0),reddit:cases.filter(item=>item.sourcePlatform==="reddit" && item.createdAt.startsWith(day.key)).reduce((sum,item)=>sum+reportCount(item),0),opened:cases.filter(item=>item.createdAt.startsWith(day.key)).length,closed:cases.filter(item=>item.createdAt.startsWith(day.key)&&item.phase==="COMPLETED").length }));
  const totalReports=cases.reduce((sum,item)=>sum+reportCount(item),0);
  const receiptCount=cases.reduce((sum,item)=>sum+item.publications.filter(reply=>["confirmed","manually_attested"].includes(reply.status)).length,0);
  const distribution=[{name:"Engineering",n:cases.filter(item=>["engineering","engineering_resolution"].includes(item.route)).length,color:"var(--ink)"},{name:"Known remedy",n:cases.filter(item=>item.route==="known_remedy").length,color:"var(--ink3)"},{name:"Engagement",n:cases.filter(item=>item.route==="social_engagement").length,color:"var(--accent)"},{name:"Review / other",n:cases.filter(item=>!["engineering","engineering_resolution","known_remedy","social_engagement"].includes(item.route)).length,color:"var(--line2)"}];
  const maximum=Math.max(1,...daily.flatMap(day=>[day.x,day.reddit]));
  const path=(key:"x"|"reddit")=>daily.map((day,index)=>`${index ? "L":"M"}${index*100} ${180-day[key]/maximum*165}`).join(" ");
  let offset=0;
  return <>
    <div className="metrics-heading"><h1>Last 7 days</h1><span className="mono">{days[0].date.toLocaleDateString("en-GB",{day:"numeric",month:"short"})} – {days[6].date.toLocaleDateString("en-GB",{day:"numeric",month:"short"})}</span></div>
    <div className="metric-stats">{[{label:"Signals recorded",value:totalReports,sub:"Original reports in this workspace"},{label:"Engineering incidents",value:distribution[0].n,sub:"Routed to protected investigation"},{label:"Cases closed",value:cases.filter(item=>item.phase==="COMPLETED").length,sub:"Outcomes retained per case"},{label:"Confirmed replies",value:receiptCount,sub:"Confirmed or manually attested"}].map(item=><div key={item.label}><span>{item.label}</span><strong>{item.value}</strong><p>{item.sub}</p></div>)}</div>
    <div className="metrics-top-grid"><section className="chart-panel"><div className="chart-heading"><h2>Signals recorded per day</h2><div className="chart-legend"><span><i className="ink"/>X</span><span><i className="orange"/>Reddit</span></div></div><div className="line-chart" role="img" aria-label="Recorded X and Reddit reports over the last seven days"><div className="chart-grid">{[maximum,Math.ceil(maximum*.75),Math.ceil(maximum*.5),Math.ceil(maximum*.25),0].map((value,index)=><div key={index}><span className="mono">{value}</span><i/></div>)}</div><svg viewBox="0 0 600 180" preserveAspectRatio="none"><path d={path("x")} fill="none" stroke="var(--ink)" strokeWidth="2"/><path d={path("reddit")} fill="none" stroke="var(--accent)" strokeWidth="2"/>{daily.map((day,index)=><g key={day.key}><circle cx={index*100} cy={180-day.x/maximum*165} r="3" fill="var(--surface)" stroke="var(--ink)" strokeWidth="2"/><circle cx={index*100} cy={180-day.reddit/maximum*165} r="3" fill="var(--surface)" stroke="var(--accent)" strokeWidth="2"/></g>)}</svg></div><div className="chart-days mono">{days.map(day=><span key={day.key}>{day.label}</span>)}</div></section>
    <section className="chart-panel"><h2>What the signals were</h2><div className="donut-wrap"><svg viewBox="0 0 120 120" width="120" height="120" aria-label="Case routing distribution"><circle cx="60" cy="60" r="48" fill="none" stroke="var(--track)" strokeWidth="14"/>{distribution.map(item=>{const length=item.n/Math.max(1,cases.length)*301.59;const previous=offset;offset+=length;return <circle key={item.name} cx="60" cy="60" r="48" fill="none" stroke={item.color} strokeWidth="14" strokeDasharray={`${length} 301.59`} strokeDashoffset={-previous}/>;})}</svg><div className="donut-legend">{distribution.map(item=><div key={item.name}><span><i style={{background:item.color}}/>{item.name}</span><span className="mono">{cases.length ? Math.round(item.n/cases.length*100):0}%</span></div>)}</div></div><p className="chart-note">{cases.length ? `${distribution[0].n} of ${cases.length} recorded cases need engineering.` : "No cases recorded in this time window yet."} Counts reflect stored case routes.</p></section></div>
    <div className="metrics-bottom-grid"><section className="chart-panel"><div className="chart-heading"><h2>Incidents opened vs closed</h2><div className="chart-legend"><span><i className="pale"/>opened</span><span><i className="ink"/>closed</span></div></div><div className="bar-chart">{daily.map(day=><div key={day.key}><div className="bar-track" style={{height:`${day.opened/Math.max(1,...daily.map(item=>item.opened))*130}px`}} title={`${day.opened} opened, ${day.closed} closed`}><span style={{height:`${day.closed/Math.max(1,day.opened)*100}%`}}/></div><span className="mono">{day.label}</span></div>)}</div><p className="chart-note">Closed counts are grouped by the incident’s intake date.</p></section>
    <section className="chart-panel"><div className="chart-heading"><h2>Production → customer reply</h2><span className="mono muted">recorded outcomes</span></div>{cases.filter(item=>item.productionVerified).slice(0,5).map(item=><Link className="outcome-row" key={item.id} href={`/cases/${item.id}`}><span className="mono">{shortId(item.id)}</span><div><span style={{width:`${item.publications.filter(reply=>["confirmed","manually_attested"].includes(reply.status)).length / Math.max(1,item.publications.length)*100}%`}}/></div><span>{item.publications.some(reply=>["confirmed","manually_attested"].includes(reply.status)) ? "replied":"pending"}</span></Link>)}{!cases.some(item=>item.productionVerified)&&<p className="metric-empty">Verified production and confirmed replies will appear here.</p>}<p className="chart-note">A verified fix does not mean the customer has been notified.</p></section></div>
    <section className="chart-panel"><div className="chart-heading"><h2>Where incidents are right now</h2><span className="mono muted">{snapshot.cases.filter(item=>item.phase!=="COMPLETED").length} open</span></div><div className="stage-funnel">{STAGES.map((stage,index)=><Link key={stage} href="/cases" title={stage} style={{flex:Math.max(.1,snapshot.cases.filter(item=>stageFor(item)===stage).length),background:stage.includes("approval") ? "var(--accent)":index===6 ? "var(--ink)":`var(--${["line2","pending","ink3","ink3","ink2"][index] || "ink3"})`}}/>)}</div><div className="stage-legend">{STAGES.map(stage=><Link href="/cases" key={stage}>{stage}<span className="mono">{snapshot.cases.filter(item=>stageFor(item)===stage).length}</span></Link>)}</div></section>
  </>;
}
